// containers
import { AccountTypeSelectBoard } from '@/modules/user/containers/account-type-select-board';

import styles from './account-type-select.module.scss';
import Image from 'next/image';
import Bg from '@/assets/images/bg-1.png';

export default function Profile() {
  return (
    <main className={styles.root}>
      <Image className={styles.bg} {...Bg} alt='background' />
      <AccountTypeSelectBoard />
    </main>
  );
}

export const metadata = {
  title: 'StyleSync | Account type',
  description: 'Generated by create next app',
};
