import '@/styles/globals.scss';
// constants
import { i18nConfig } from '@/modules/internationalization/constants/i18n.constants';
// providers
import { TrpcProvider } from '@/utils/trpc-provider';
// types
import type { ChildrenProp } from '@/modules/core/types/react.types';
import type { PageParams } from '@/modules/core/types/next.types';

export default function RootLayout({
  children,
  params,
}: ChildrenProp & PageParams) {
  return (
    <html lang={params.lang}>
      <body>
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ lang: locale }));
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
