import '@/styles/globals.scss';
import { type ReactNode } from 'react';

export const metadata = {
  title: 'StyleSync | Tennisha’s Beauty',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
