import clsx from 'clsx';
// components
import { ProfessionalInfoBigCard } from '@/modules/user/containers/professional-info-big-card';
import { AboutMe } from '@/modules/user/components/about-me';
import { GallerySection } from '@/modules/user/components/gallery-section';
import { UserServices } from '@/modules/user/components/user-services';
import { ProfessionalProfileTabs } from '@/modules/user/components/professional-profile-tabs';
// utils
import { pageGuard } from '@/modules/core/utils/route.utils';

import styles from './profile.module.scss';

export default async function Profile() {
  await pageGuard({
    require: {
      userType: true,
      onboarding: true,
    },
  });

  return (
    <main className={styles.root}>
      <section className={clsx(styles.section, styles.headerSection)}>
        <ProfessionalInfoBigCard />
      </section>
      <section className={clsx(styles.section, styles.tabsSection)}>
        <ProfessionalProfileTabs />
      </section>
      <div className={styles.divider} />
      <div className={styles.sectionGroup}>
        <section
          className={clsx(styles.section, styles.block)}
          id='profile-about'
        >
          <AboutMe />
        </section>
        <section
          className={clsx(styles.section, styles.block)}
          id='profile-services'
        >
          <UserServices />
        </section>
        <section
          className={clsx(styles.section, styles.block)}
          id='profile-gallery'
        >
          <GallerySection />
        </section>
      </div>
    </main>
  );
}

export const metadata = {
  title: 'StyleSync | Tennisha’s Beauty',
  description: 'Generated by create next app',
};
