import '@/styles/globals.scss';
import { type ReactNode } from 'react';
// providers
import { TrpcProvider } from '@/utils/trpc-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}
