import '@/styles/globals.scss';
import { type ReactNode } from 'react';
// providers
import { Header } from '@/modules/core/containers/header';

export const metadata = {
  title: 'StyleSync | Tennisha’s Beauty',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
