name: 'Svg'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Use Yarn
        run: npm install -g yarn@1

      - name: Install dependencies
        run: yarn install

      - name: Run optimization script
        run: node scripts/svg-optimize.js

      - name: Verify
        run: |
          if [ -n "$(git diff --name-only -- src/assets/icons/)" ]; then
            echo "Some SVG files were not optimized. Run 'node scripts/svg-optimize.js' in the root of project. Then, commit changes."
            exit 1
          fi
